import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import { inter } from "./ui/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${inter.className} antialiased flex flex-col h-screen`}
      >
        <header className="bg-slate-400 p-2">
          <Header/>
        </header>
          {children}
        <footer className="flex flex-row justify-between px-8 pt-8 pb-6 items-center border-t border-primary-content">
          <Footer/>
        </footer>
      </body>
    </html>
  );
}
